/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

function countFactors(num)
{
	var i = 0, count = 0, n = 1;
    if (num % 2 !== 0) // Trying to optimize by skipping all even factors if number is odd
    {
        n = 2;
    }
	for (i = 0; i <= Math.sqrt(num); i += n)
	{
		if (num % i === 0)
		{
			count += 2;
		}
	}
	return count;
}

function eulerTwelve(numF)
{
	var i = 0, triNum = 0, countF = 0;
	for (i = 1; ; i++)
	{
        triNum += i;
		countF = countFactors(triNum);
		if (countF >= numF)
		{
			return triNum;
		}
	}
}

eulerTwelve(500);